export const colombianPhrases: any = {
  "¿A cómo tienes [objeto]?": "What are you charging for [object]?",
  "¿A cuánto está?": "What’s the price (today)?",
  "A escondidas de": "Hidden from… / behind someone’s back…",
  "A lo mejor": "Another way to say “maybe” (along with “de pronto”, “tal vez”, “quizás” etc).",
  "Abrazos": "Hugs. A typical way to sign off electronic messages and emails.",
  "Acercarse a alguien": "To go up to someone.",
  "Ahí en la lucha / ahí voy": "‘Getting there’ / ‘battling on’ (responses for when someone asks how you are).",
  "Ahora / ahorita / ahoritica": "Meaning depends on context, but can be “now”, “in a little bit”, “later” or even “never”. To definitely say “now” go for “ya“.",
  "Ahora mismo": "Right now.",
  "Ahorita más tarde": "In a little bit, later.",
  "Algo así / Algo por el estilo": "Something like that.",
  "Algo es algo, (peor es nada)": "The Spanish equivalent of “something is better than nothing”.",
  "Aliviadito": "The diminutive version of ‘(estar) aliviado’ meaning “to have eased up” or for a problem to have got better.",
  "Amanecimos…": "As well as describing the action of the sun rising, Colombians sometimes use the verb “amanecer” as a way to describe how they feel on waking (like we saw in the greeting “¿Cómo amaneciste?”). For example, “amanecimos medio enguayabitos” is “we woke up a bit hungover”, and “hoy amanecí con ganas de café” (“I woke up this morning with a craving for coffee”).",
  "Amar a alguien": "To love someone (stronger than ‘querer a alguien’).",
  "Amigo/a con derechos": "“Friend(s) with benefits” – one of several ways to talk about seeing someone casually.",
  "Amigovio/a": "A casual relationship; somewhere between being friends and being boyfriend and girlfriend.",
  "Amiguita": "When used by men, it means girls that they are seeing casually (or that they are trying to “conquistar”).",
  "Apreciar a alguien": "To care for someone a lot, to think very highly of someone.",
  "Arrocito en bajo": "A potential love interest who you’re keeping “on the backburner”.",
  "¡Así de sencillo!": "It’s that straight forward / it’s as easy as that!",
  "(Un) bacán / (una) bacana": "A cool person.",
  "Bacano": "Cool / really good (Medellín).",
  "‘Barman’": "Barman (obviously). There are a few more examples of English words Colombians regularly use in their conversations.",
  "¿Bien o no? / ¿Bien o qué?": "All good? (Greeting)",
  "Bien/demasiado borracho": "Really drunk.",
  "Buena gente": "A good person (applies for singular, plural, male and female).",
  "Buenas": "‘Morning / ‘afternoon / ‘evening.",
  "Bulla": "A more common word than “ruido” in Colombia to describe noise.",
  "Cachaco/a": "Mainly used to refer to people from the capital, Bogotá. If used along the Caribbean coastal region, it means anyone from the interior of the country.",
  "Cada ocho días": "Every week.",
  "Cada quince días": "Every two weeks (lit. every fifteen days).",
  "Cada veinte días": "Every three weeks (lit. every twenty days).",
  "Caerle (a alguien)": "To hit on someone. Can also mean something like ‘to drop by’ or ‘to meet up’ with someone.",
  "Caleta": "An illegal stash of weapons (or sometimes cash). Usually heard in the context of insurgent groups or drug traffickers.",
  "Cali es Cali. Lo demás es loma": "Cali is the best city in the world (lit. “Cali is Cali. Everything else is just a hill” i.e. Cali is above all else).",
  "Cariñoso/a": "Affectionate.",
  "Carrera": "A journey in a taxi (also a university degree, a race, or a career).",
  "Cervecita": "Beer.",
  "Chau": "Bye.",
  "Chévere": "Cool / really good (more common in Bogotá).",
  "Chevito": "The diminutive of ‘chévere’.",
  "Chimba": "Awesome / amazing / fantastic.",
  "Chino/a": "Another word for a cute person.",
  "Chismoso/a": "A person who loves to gossip.",
  "Chocho/a": "In love.",
  "Chucha": "Very far away (only used in Bogotá).",
  "Churro/a": "Cute person (also “lindo/a”).",
  "Claro": "Of course.",
  "Coger": "To have sex (used a lot in Colombia, less offensive than in other countries).",
  "Cola": "A line (as in, ‘waiting in line’).",
  "Comer cuento": "To believe everything you’re told (sometimes used when someone is being teased/joking).",
  "Con mucha frecuencia": "Very often.",
  "Corroncho/a": "A pejorative term to describe people from the Caribbean coast. Sometimes used in a more playful way by ‘corronchos’ themselves.",
  "Cuenta / Cuentas": "Bill / bills.",
  "Culear": "To have sex (vulgar).",
  "Culicagado/a": "A very offensive term to describe someone (‘culicagado’ literally means “shit-fucked”).",
  "Dar papaya": "To give someone the opportunity to take advantage of you (like leaving your phone on the table in a crowded bar).",
  "De una": "Right away / immediately.",
  "De una vez": "All at once / at the same time.",
  "De una vez por todas": "Once and for all.",
  "Dejado/a": "Lazy.",
  "Desparchado/a": "Bored (only used in Bogotá).",
  "Desparpajado/a": "Unfocused, all over the place.",
  "Depronto": "Maybe / perhaps.",
  "Desvelado/a": "Sleep-deprived / can’t sleep.",
  "Dicho sea de paso": "By the way.",
  "Dizque": "Supposedly (but it’s not actually true).",
  "Dormir a pierna suelta": "To sleep like a log.",
  "Dormir la mona": "To sleep off a hangover.",
  "Echar los perros": "To hit on someone.",
  "Echarse los perros": "To hit on someone.",
  "Echarse una cana al aire": "To have a bit of fun / a night out / a fling.",
  "El/la de atrás": "The person behind you.",
  "El/la de en frente": "The person in front of you.",
  "El que tiene tienda, que la atienda": "Literally, “he who has a shop, looks after it”. The Colombian equivalent of “if you break it, you buy it”.",
  "El tiempo es oro": "Time is money.",
  "El que sabe, sabe": "He/she who knows, knows (i.e., someone who’s an expert).",
  "En serio / En realidad / De verdad": "Seriously / Really.",
  "En una de esas": "Maybe / perhaps.",
  "Enguayabado/a": "Hungover.",
  "Estar berraco/a": "To be very angry.",
  "Estar bolo/a": "To be very angry (in Medellín).",
  "Estar de buenas / de buenas": "To be in a good mood / lucky.",
  "Estar en la pachanga": "To be in the party spirit.",
  "Estar en el horno": "To be in trouble / in a difficult situation.",
  "Estar en la lona": "To be down and out / defeated.",
  "Estar en las mismas": "To be in the same situation / in the same boat.",
  "Estar en su salsa": "To be in your element.",
  "Estar hasta las manos": "To be up to your neck (in trouble / in debt / etc).",
  "Estar maluco/a": "To be ill / unwell.",
  "Estar pela’o/a": "To be broke.",
  "Estar sin un peso": "To be broke.",
  "Estar soltero/a": "To be single.",
  "Éxito": "Good luck / have a good day.",
  "Falta mucho / falta poquito": "It’s a long way / It’s not far.",
  "Fresco/a": "It’s OK / don’t worry about it.",
  "Fresa": "Snobby person (can be used as an adjective – “Juan es muy fresa”).",
  "Fuácata": "Really good / fantastic / excellent.",
  "Gonorrea": "A very offensive term to describe someone (‘gonorrea’ literally means “gonorrhea”).",
  "Guaro": "A small bottle of aguardiente, a popular alcoholic drink in Colombia.",
  "Hacer el oso": "To do something embarrassing.",
  "Hacer el pelota": "To suck up to someone / to brown-nose.",
  "Hacer el tirpo / tirpa": "To mess around / to waste time.",
  "Hacer el tonto / tonta": "To act stupid.",
  "Hacer fila": "To wait in line.",
  "Hacer fresco": "To keep cool / to stay chill (used in hot weather).",
  "Hacer la vista gorda": "To turn a blind eye.",
  "Hacerle la pelota a alguien": "To suck up to someone / to brown-nose.",
  "Hasta las patas": "Completely drunk.",
  "Hay que echarle los perros a alguien": "We have to hit on someone.",
  "Hijueputa": "A very offensive term to describe someone (‘hijueputa’ literally means “son of a bitch”).",
  "Hijueputiando": "An adverb used to describe something you’re doing when you’re angry or frustrated (like “¡Estoy hijueputiando!”)",
  "Hincha": "A football fan.",
  "Hincha pelotas": "A person who’s a pain in the neck.",
  "Hoy en día": "Nowadays / these days.",
  "Jalado/a": "Drunk (only used in Medellín).",
  "Jarto/a": "Fed up / tired of something.",
  "Joda": "A problem / a pain in the ass. Can also be used to talk about partying.",
  "Juepucha": "An expression of surprise or frustration (like “wow” or “darn it”).",
  "Ligar": "To flirt / to hit on someone.",
  "Llevarse bien / mal": "To get on well / badly with someone.",
  "Llueve sobre mojado": "When it rains, it pours (i.e., when something bad happens, more bad things happen).",
  "Mamar gallo": "To have a laugh (lit. “to suck a rooster”).",
  "Man / parce": "Dude / mate.",
  "Mamar": "To have a laugh (used a lot in Medellín).",
  "Mamarse": "To get drunk (only used in Bogotá).",
  "Me cae bien / mal": "I like / dislike (him/her).",
  "Me estás tomando el pelo": "You’re pulling my leg.",
  "Mijo/a": "Son / daughter (can also be used to refer to someone else’s child).",
  "Mondá": "What a load of rubbish!",
  "Mono/a": "A person from the coast (Atlántico, Bolívar, Cesar, La Guajira, Magdalena, Sucre) who doesn’t like working and who tries to live off other people (off their wife or girlfriend, for example).",
  "Mucho gusto": "Nice to meet you.",
  "Nada del otro mundo": "Nothing special.",
  "No aguanto": "I can’t bear it.",
  "No faltaba más": "Of course.",
  "No importa": "It doesn’t matter.",
  "No joda / No sea mala leche": "Don’t be a pain in the ass / Don’t be nasty.",
  "No le llega ni a los tobillos": "He/she doesn’t even come close.",
  "No sea maluco/a": "Don’t be nasty.",
  "No sea sapo / sapito": "Don’t be nosey.",
  "No tener pelos en la lengua": "To speak your mind / to not mince your words.",
  "Nunca falta un roto para un descosido": "There’s someone out there for everyone.",
  "Nunca falta quien le eche bala": "There’s always someone who will have a go.",
  "Nunca falta quien mete la cuchara": "There’s always someone who will butt in.",
  "O sea": "In other words.",
  "Oído al tambor": "Got it / I heard you.",
  "Parce": "Mate / dude (more common in Medellín).",
  "Pasar la raya": "To go too far.",
  "Peaje": "Toll booth.",
  "Pelear con alguien": "To argue with someone.",
  "Perra / perrero": "A player (someone who is cheating on their partner).",
  "Picar": "To chop something (like vegetables).",
  "Pilas": "Be careful / watch out.",
  "Pillar cachos": "To cheat on someone (lit. “to catch horns”).",
  "Pisto": "Money.",
  "Poner el dedo en la llaga": "To rub salt in the wound.",
  "Poner los cachos": "To cheat on someone.",
  "Por las buenas o por las malas": "One way or another / whether you like it or not.",
  "Por lo visto": "Apparently.",
  "Qué berraquera": "What a nuisance / what a drag.",
  "Qué bobo": "How silly.",
  "Qué bruta": "How silly.",
  "Qué desparche": "What a drag.",
  "Qué grosería": "How rude.",
  "Qué huevo": "How boring.",
  "Qué nota": "How boring.",
  "Qué oso": "How embarrassing.",
  "Qué pena": "How embarrassing.",
  "Qué pesar": "What a pity.",
  "Rabón/a": "Grumpy person.",
  "Rayar (con)": "To be too nosey / to stick your nose in.",
  "Recoger a alguien": "To pick someone up (usually in a car).",
  "Relajo": "Fun / mess / hassle.",
  "Rolo/a": "Someone from Bogotá (can also be used to refer to someone from Bogotá).",
  "Sabroso/a": "Delicious.",
  "Sano/a": "Healthy.",
  "Ser buena gente": "To be a good person.",
  "Ser el/la parche": "To be the life and soul of the party.",
  "Ser gomelo/a": "To be snobby (used more in Bogotá).",
  "Ser parche": "To be fun / the life and soul of the party.",
  "Ser pelado/a": "To be a good guy / a good person.",
  "Ser pingo/a": "To be a good guy / a good person (only used in Bogotá).",
  "Ser un/a berraco/a": "To be very good at something.",
  "Ser un/a guache/a": "To be an idiot / to be stupid.",
  "Ser un/a pelmazo/a": "To be a pain in the neck.",
  "Ser un/a peluquero/a": "To be a wimp.",
  "Ser un/a sapo/a": "To be a gossip / to be a nosey parker.",
  "Si da papaya": "If you give someone the opportunity to take advantage of you (like leaving your phone on the table in a crowded bar).",
  "Si me da papaya": "If you give me the opportunity to take advantage of you (like leaving your phone on the table in a crowded bar).",
  "Sobrado/a": "Overconfident / big-headed.",
  "Sos vos / Sos tú": "It’s you.",
  "Suave": "Take it easy / calm down.",
  "Tablas": "You’re used to it / you’re an old hand.",
  "Tal vez / quizás / acaso": "Maybe / perhaps.",
  "Tener berraquera": "To have the balls to do something.",
  "Tener rabo de paja": "To have a guilty conscience.",
  "Tener un mal genio": "To be grumpy.",
  "¡Uy!": "Wow! / Ooh!",
  "Vaina": "Thing / thingamabob.",
  "Vea pues": "Well then / so there you go.",
  "Vergón / Verga": "Really cool / really good.",
  "Volarse": "To be really good.",
  "Ya": "Now / already.",
  "Ya estoy amañado": "I’m comfortable here / I feel at home here."
}
